### ISSUE TITLE
Поправить средний рейтинг

### ISSUE THREAD

**Issue by adzhumurat** [inomeri/mai_data_management#1]
https://github.com/inomeri/mai_data_management/blob/69ee9774f1a26a4b78e71039bfb157790325e967/Simple%20SQL%20HW/hw1.sql#L44

Тут получается у вас никак не связаны "внешний" и "внутренний" запрос

Нужено во внутреннем запросе выводить дополнительно MovieId, а во "внешнем" запросе воспользоваться, например, оператором `IN`

**Comment by inomeri** [comment]
Исправила.
https://github.com/inomeri/mai_data_management/blob/14c7d78a7954557df16dbe11a3fb88e53c6a7e11/Simple%20SQL%20HW/hw1.sql#L43
